apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ui-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin123
        - name: POSTGRES_DB
          value: basic3tier
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pv-claim          
