apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: ui-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: wayne7635/ui-3tier
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: ui-namespace
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001